### GET /hello
GET http://localhost:8081/hello

### POST /echo
POST http://localhost:8081/echo
Content-Type: text/plain

Hello, Server!

### PUT /put
PUT http://localhost:8081/put
Content-Type: text/plain

This is a PUT request

### PATCH /patch
PATCH http://localhost:8081/patch
Content-Type: text/plain

This is a PATCH request

### DELETE /delete
DELETE http://localhost:8081/delete

### GET /params with headers and body
GET http://localhost:8081/params
Content-Type: application/json
Authorization: Bearer abcdef123456

{
  "key": "value"
}

### GET /params with headers only
GET http://localhost:8081/params
Content-Type: application/json
Authorization: Bearer abcdef123456

### GET /params with body only
GET http://localhost:8081/params

{
  "key": "value"
}

### GET /params without headers and body
GET http://localhost:8081/params

### Non-existing endpoint
GET http://localhost:8081/nonexistent

### Invalid HTTP method
POST http://localhost:8081/hello